# Generated by Django 5.1.7 on 2025-03-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_industry_lead_priority_lead_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email_open_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lead',
            name='engagement_status',
            field=models.CharField(choices=[('Engaged', 'Engaged'), ('Not Engaged', 'Not Engaged'), ('Pending Follow-Up', 'Pending Follow-Up')], default='Pending Follow-Up', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead')),
            ],
        ),
    ]
